The code problems sets in this excercise sheet are taken from many helpful resources.   
Check them out for further practice:     

https://www.kaggle.com/utsav15/100-numpy-exercises  
https://www.w3resource.com/python-exercises/numpy/index.php   
https://www.machinelearningplus.com/python/101-numpy-exercises-python/  
https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/    (Multiple solutions per problem)   
https://favtutor.com/blogs/numpy-exercises-python    

Level your coding skills by solving challenges:   
https://www.hackerrank.com/domains/python/numpy/difficulty/all/page/1  


In [1]:
import numpy as np


# Question: Create a null vector of size 10


In [4]:

Z= np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Question: Create a vector with values ranging from 10 to 49

In [12]:
Z=np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


# Question: Reverse a vector (first element becomes last)


In [15]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
Z2 = np.flip(Z)            # https://numpy.org/doc/stable/reference/generated/numpy.flip.html 
print(Z2)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
np.arange(50,0,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


# Question: Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


# Question: Find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
Z=np.array([1,2,0,0,4,0])       # value 
Z[Z>0]

array([1, 2, 4])

In [36]:
idx=Z.nonzero()      # index
print(idx)
print(idx[0])
print(Z[idx])
print(Z[idx[0]])


(array([0, 1, 4], dtype=int64),)
[0 1 4]
[1 2 4]
[1 2 4]


# Question: Create a 10x10 array with random values and find the minimum, maximum and mean values    


# Answer:

In [47]:

Z= np.random.default_rng().random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print (Zmin, Zmax, Zmean)

0.011077608391733662 0.9735914158861056 0.42926317792506674


In [131]:
# float numberabs 
Z=np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print (Zmin, Zmax, Zmean)


0.01957083634039236 0.9962665605466694 0.4625893486057948


In [134]:
# integer numberabs 
Z=np.random.randint(0,10,(10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print (Zmin, Zmax, Zmean)

0 9 4.07



# Question: What is the result of the following expressions?


print(0 * np.nan)  
print(np.nan == np.nan)   
print(np.inf > np.nan)  
print(np.nan - np.nan)   
print(np.nan in set([np.nan]))   
print(0.3 == 3*0.1)   

# Answer


In [81]:
print(0*np.nan)
print (np.nan == np.nan)
print(np.inf> np.nan)
print(np.nan- np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


In [83]:
set([np.nan])

{nan}

# Question: Write a NumPy program to convert a list and tuple into arrays.

List to array: [1 2 3 4 5 6 7 8]   
Tuples to array: ((8, 4), (6,1), (2, 3))

# Answer:

In [86]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]        # only one function
print("List to array: ") 
print(np.array(my_list))
my_tuple =((8, 4), (6,1), (2, 3))
print("Tuples to array: ")
print(np.array(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuples to array: 
[[8 4]
 [6 1]
 [2 3]]


# Question: Write a NumPy program to append values to the end of an array. 
original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]    


# Answer:

In [89]:
x = [10, 20, 30]
print(type(x))
print("original array: ") 
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]]) 
print("After append values to the end of the array: ")
print(x)
print(type(x))                                 #  X change to  array
                                               # array after creation can not change or append   you can concat , hstack   
x.append([88,88])                               # numpy array unlike list do not have  append method  

<class 'list'>
original array: 
[10, 20, 30]
After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [94]:
x=np.array([1,2,3])
y=[4,5]
z=np.concatenate((x,y))    # return new object 
print(x,z)

[1 2 3] [1 2 3 4 5]


# Question: How to add a border (filled with O's) around an existing array?   


# Answer:

In [98]:

Z= np.ones((5,5))
z = np. pad (Z, pad_width=1, mode='constant', constant_values=0) # https://numpy.org/doc/stable/reference/generated/numpy.pad/html
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Question: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?



In [101]:
np.unravel_index(100,(6,7,8))   # 100 is index

(1, 5, 4)


## Question: Normalize a 5x5 random matrix


# Answer:

In [111]:
Z=np.random.random((5,5))
Z=(Z-np.mean(Z))/(np. std (Z))
print(Z)

[[ 0.84766754 -0.88472632 -1.07281623  1.55705344  1.14725457]
 [-0.06619051  0.82803025 -1.48101461 -0.44355781 -1.47065911]
 [ 0.07694505  1.53388716  0.37754962  0.9399324  -0.47126207]
 [ 0.4392101  -1.03758324 -0.93756258  0.59718859 -1.47485861]
 [ 1.50135534 -1.47472137  0.00363626  0.18074432  0.78449781]]



## Question: Given a 1D array, negate all elements which are between 3 and 8, in place ¶

# Answer:

In [121]:
z=np.arange(11)
z[(z>=3) & (z<=8)]*=-1
z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])


# Question: How to find common values between two arrays?

In [137]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,5)
print(z1)
print(z2)

print(np.intersect1d(z1,z2))

[3 7 2 8 4 2 5 9 7 4]
[9 4 3 8 4]
[3 4 8 9]


## Question: Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


Array1: [0 10 20 40 60]   
Array2: [0, 40]


In [140]:
array1= np.array([0, 10, 20, 40, 60])
array2=[0, 40]
print("Compare each element of array1 and array2")
print (np.in1d(array1, array2))

Compare each element of array1 and array2
[ True False False  True False]


## Question: How to get all the dates corresponding to the month of July 2016?

## Answer:


In [141]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')    # d for day
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## Question: Extract the integer part of a random array using 5 different methods

In [142]:
Z = np.random.uniform(0,10,10)

print(z)
print (Z - Z%1) 
print (np.floor(Z))
print (np.ceil(Z)-1) 
print (Z.astype(int))
print (np. trunc(Z))


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
[9. 2. 9. 7. 0. 9. 6. 6. 5. 9.]
[9. 2. 9. 7. 0. 9. 6. 6. 5. 9.]
[9. 2. 9. 7. 0. 9. 6. 6. 5. 9.]
[9 2 9 7 0 9 6 6 5 9]
[9. 2. 9. 7. 0. 9. 6. 6. 5. 9.]


## Question: Consider two random array A and B, check if they are equal    


## Answer:


In [144]:

A = np.random.randint(0,20,5)
B= np.random.randint(0,20,5)
print(A) 
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal) 
#Checking both the shape and the element values, no tolerance (values have to be exactly equal) equal np.array_equal(A,B)
print(equal)

#check as well:
# https://numpy.org/doc/stable/reference/generated/numpy.isclose.html

[15  1  4 16  9]
[ 8 18  5 14  1]
False
False


## Question: How to find the closest value (to a given scalar) in a vector?

## Answer:


In [149]:
Z = np.arange(100)
print(Z)
v = np.random. uniform(0,100)
print(v)
index=(np.abs (Z-v)).argmin()  # return index
print(Z[index])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
87.4271178091607
87


## Question: Find the nearest value from a given value in an array


## Answer:

In [155]:
Z = np.random.uniform (0,1,(10,10)) 
z= 0.5
m = Z.flat[np.abs(Z -z).argmin()]
print(Z)
print(m)

[[0.25878516 0.58563105 0.76978895 0.46096721 0.19221511 0.43228517
  0.75218493 0.47703473 0.24918576 0.51541377]
 [0.86805747 0.37874849 0.97234899 0.93229045 0.181772   0.83606361
  0.61552897 0.0686522  0.50744892 0.15229088]
 [0.11612864 0.47152026 0.8171081  0.35444095 0.15807752 0.59650809
  0.28173673 0.23254961 0.0177342  0.81753942]
 [0.40536573 0.99700307 0.33304045 0.43794094 0.13854308 0.28111357
  0.55174081 0.74302798 0.92826921 0.77938456]
 [0.88307031 0.74785609 0.12663934 0.74255975 0.57115172 0.4320776
  0.25664806 0.11371826 0.26077485 0.05529769]
 [0.55730639 0.13263841 0.1265028  0.48745524 0.87689718 0.50333887
  0.38171732 0.58651283 0.41451005 0.16061268]
 [0.03463375 0.54445654 0.63409017 0.96030918 0.43606009 0.00109554
  0.93091013 0.76996185 0.88369688 0.03050817]
 [0.2747193  0.97722493 0.49912384 0.56983553 0.67773375 0.19589609
  0.94015804 0.40041766 0.01839083 0.84249045]
 [0.0732266  0.12514853 0.25937232 0.2925369  0.73993823 0.165975
  0.43242586 0.


## Question: Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.


## Answer:

In [157]:
x= np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10", x[x>10])
print("Their indices are", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 [20 20 30 40]
Their indices are (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))



## Question: Write a NumPy program to save a NumPy array to a text file.

## Answer:

In [159]:
a = np.arange(1.0, 20.0, 0.5)
print(a)
np.savetxt('file.txt', a, delimiter=',')  
# When you open the file will will find no commas #delimiter arg: string or character separating columns.    
#newlinestr arg: String or character separating lines.  
#Read more https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html
#SELF-STUDY: You'll neeed them for later courses
# numpy.Load, numpy.save, numpy.Loadtxt, numpy.savetxt, numpy.genfromtxt, 
#numpy.fromstring, numpy.ndarray.tofile, numpy.ndarray.tolist, numpy.array2string

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]



## Question: How to read the following file?



## Answer:

In [170]:
from io import StringIO
#Fake file
s = StringIO(""" 1, 2, 3, 4, 5\n
                6, , , 7, 8\n 
               , , 9,10,11\n""")

Z= np.genfromtxt(s, delimiter=",", dtype=int) 
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]



## Question: What is the equivalent of enumerate for numpy arrays?


## Answer:

In [176]:
 Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## Question: Subtract the mean of each row of a matrix

## Answer:

In [180]:
X = np.random.rand(5, 10)
print(X)
# Recent versions of numpy
Y = X-X.mean (axis=1, keepdims=True)          # If keepdims is set to True, the result will broadcast correct
                                                # against the input array.

# Older versions of numpy
Y = X-X. mean (axis=1).reshape(-1, 1)
print(Y)


[[0.82862165 0.5837749  0.33591579 0.8172731  0.02237039 0.82232287
  0.35518439 0.94585394 0.49032463 0.4620941 ]
 [0.3208792  0.06745812 0.99474238 0.17767682 0.27117447 0.4432621
  0.45785127 0.95538041 0.61227005 0.15404405]
 [0.71971168 0.46585858 0.69959103 0.31014454 0.52474977 0.7482676
  0.71362015 0.69944215 0.29613306 0.34588875]
 [0.89079772 0.33691547 0.86331806 0.8613588  0.19825764 0.22706452
  0.24703547 0.13264401 0.79236063 0.09631393]
 [0.75017476 0.37625106 0.34923124 0.06499918 0.8890348  0.43991662
  0.55243753 0.9703114  0.84180569 0.28107154]]
[[ 0.26224808  0.01740132 -0.23045779  0.25089952 -0.54400319  0.2559493
  -0.21118918  0.37948037 -0.07604895 -0.10427947]
 [-0.12459469 -0.37801577  0.54926849 -0.26779707 -0.17429942 -0.00221179
   0.01237738  0.50990653  0.16679616 -0.29142983]
 [ 0.16737095 -0.08648215  0.1472503  -0.24219619 -0.02759096  0.19592687
   0.16127942  0.14710142 -0.25620767 -0.20645198]
 [ 0.4261911  -0.12769116  0.39871143  0.39675217 -0

## Question: How to sort an array by the nth column?


## Answer:

In [182]:

Z = np.array([[5, 2, 9], [1, 1, 15], [7, 10, 3]])
print(Z)
print(Z[Z[:0].argsort()])
print(Z[Z[:,1].argsort()])
print(Z[Z[:,2].argsort()])

[[ 5  2  9]
 [ 1  1 15]
 [ 7 10  3]]
[]
[[ 1  1 15]
 [ 5  2  9]
 [ 7 10  3]]
[[ 7 10  3]
 [ 5  2  9]
 [ 1  1 15]]


## Question: Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')   
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

## Answer:


In [183]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis') 
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)   # x is indexs
 

[1 3 2 4 0]


## Question: How to tell if a given 2D array has null columns?

In [189]:
Z= np.random.randint(0, 3, (3,10))
print (Z)
print((~Z.any (axis=0)).any())       # any() Test whether any array element along a given axis eqvaluates to none zero value
                                      # any return true for  none empty value

print (Z.any (axis=0))
print(~Z.any (axis=0)) 
print((~Z.any (axis=0)).any())


[[1 2 0 0 2 0 0 0 0 0]
 [2 2 0 0 2 1 0 0 1 1]
 [0 1 1 2 1 0 0 2 2 0]]
True
[ True  True  True  True  True  True False  True  True  True]
[False False False False False False  True False False False]


## Question: Considering a four dimensions array, how to get sum over the last two axis at once?  
   

## Answer:

In [196]:
A= np.random.randint(0, 10, (3,4,3,4))
                                          # solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum =A.sum(axis=(-2,-1))                   # -1 for last index  
print(sum)                                  # -2 befor last 



[[54 65 63 23]
 [55 47 62 50]
 [48 54 36 57]]


##  Related: Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
happens in avgpooling [batch,channel, hight, width]

## Answer:

In [205]:
Z= np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat (Z, np.arange(0, Z.shape[0], k), axis=0),   #reduce row
                                         np.arange(0, z.shape[1], k), axis=1 )   # reduce col

print(S)

#https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html
# Performs a (Local) reduce with specified slices over a single axis.


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]



## Question: How to swap two rows of an array?
## Answer:

In [207]:

A = np.arange(25).reshape(5,5) 
print(A)

A[[0,1]] =A[[1,0]]   # can not do this for swap row by col  ony col wigh col  or row with row 

print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Question: How to get the n largest values of an array
happens in one-to-many classifier (top n predictions)

## Answer:

In [212]:
Z= np.arange(10000)
np.random.shuffle(Z)
n = 5
# fast
print (Z[np.argsort(Z)[-n:]])
# slow
print (Z[np.argpartition (-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9995 9999 9997 9998]


### Question: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R =    
### [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?   

simulating sequential model training feed
## Answer:

In [219]:
from numpy.lib import stride_tricks
Z= np.arange(1,15, dtype=np. uint32)
R = stride_tricks.as_strided(Z, (11,4), (4,4)) # do not know what is  (4,4)
print(R)




[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
