In [2]:
import numpy as np

# Broadcasting
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.  
# Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:  
• Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left)  side.  
• Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the   other shape.  
• Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.




# Boadcast EX1

In [3]:
M=np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
N=np.arange(3)
N.shape

(3,)

Let's consider an operation on these two arrays. The shape of the arrays are
- ` M. shape (2, 3)`
- `a.shape(3,)`
  
We see by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:   
- ` M. shape-> (2, 3) `
- `a.shape -> (1, 3)`  
By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:  
- `M.shape-> (2, 3)`  
- `  a.shape-> (2, 3) `  
The shapes match, and we see that the final shape will be (2, 3):    

In [5]:
N*M

array([[0., 1., 2.],
       [0., 1., 2.]])

In [6]:
N+M

array([[1., 2., 3.],
       [1., 2., 3.]])

# Boadcast EX2

In [7]:
a=np.arange(3).reshape((3,1))
a

array([[0],
       [1],
       [2]])

In [8]:
b=np.arange(3)  
b

array([0, 1, 2])

In [9]:
b*a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

# Again, we'll start by writing out the shape of the arrays:   
- `a.shape (3, 1)`  
- ` b.shape (3,)`  
Rule 1 says we must pad the shape of b with ones:   
- `a.shape-> (3, 1)`   
- ` b.shape-> (1, 3)`   
And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:   
- `a.shape-> (3, 3)`  
- `b.shape (3, 3)`
  
Because the result matches, these shapes are compatible. We can see this here:

# brodcast ex3

In [15]:
M=np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
a=np.arange(3) 
a.shape

(3,)

This is just a slightly different situation than in the first example: the matrix ` M` is transposed.how does this affect the calculation?   
The shape of the arrays are   
M.shape = (3,2)    
a.shape = (3,)  
Again,
rule 1 tells us that we must pad the shape of a with ones:   
-  M. shape-> (3, 2)
- a.shape-> (1, 3)
  
By rule 2,the first dimension of a is stretched to match that of M:   
-  M. shape-> (3, 2)
- a.shape-> (3, 3)
step#3:   
      err

In [17]:
a+M

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

Note the potential confusion here: you could imagine making a and M compatible by, say, padding a 's shape with ones on the right rather than the
left. But this is not how the broadcasting rules work! That sort of flexibility might be useful in some cases, but it would lead to potential areas of ambiguity.

If right-side padding is what you'd like, you can do this explicitly by reshaping the array (we'll use the np.newaxis):

In [10]:
# first solution 
a.reshape((3,1))


(3, 1)

In [28]:
a[:,np.newaxis]   

array([[0],
       [1],
       [2]])

In [29]:
M+a[:,np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# An Example of using Broadcasting in Practice

## Centering an array

One commonly seen example is when centering an array of data.
Imagine you have an array of 10 observations, each of which consists of 3 values.

In [31]:
X=np.random.random((10,3))
X

array([[0.26785895, 0.82867487, 0.71720925],
       [0.33896964, 0.20199527, 0.87228782],
       [0.27514706, 0.29134827, 0.94187401],
       [0.31781435, 0.89866802, 0.06712362],
       [0.36660508, 0.73122117, 0.26582218],
       [0.15998077, 0.49184711, 0.15985571],
       [0.76987604, 0.90669982, 0.79433955],
       [0.2030382 , 0.18050802, 0.11031318],
       [0.59782182, 0.3683553 , 0.39673487],
       [0.65483987, 0.59384801, 0.91425047]])

In [33]:
Xmean=X.mean(0)             # zero  mean first axis   (10,3)-->(1,3)
Xmean                      #  mean for each columns

array([0.39519518, 0.54931659, 0.52398107])

In [35]:
X_centered=X-Xmean                       # 
X_centered

array([[-0.12733623,  0.27935828,  0.19322819],
       [-0.05622553, -0.34732131,  0.34830675],
       [-0.12004812, -0.25796831,  0.41789294],
       [-0.07738083,  0.34935143, -0.45685745],
       [-0.0285901 ,  0.18190458, -0.25815889],
       [-0.2352144 , -0.05746947, -0.36412535],
       [ 0.37468087,  0.35738323,  0.27035849],
       [-0.19215698, -0.36880856, -0.41366789],
       [ 0.20262664, -0.18096128, -0.12724619],
       [ 0.25964469,  0.04453142,  0.3902694 ]])