# Creating Structured Arrays


In [1]:
import numpy as np

In [2]:
person_data_def = [('name', 's6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')] 
person_data_def

[('name', '56'), ('height', 'f8'), ('weight', 'f8'), ('age', '18')]

regarding types may need to check this: https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes-constructing

In [10]:
people_array = np.zeros( (5), dtype=[('name', 'S6'),('height','f8'), ('weight' ,'f8') ,('age' ,'i8')])
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0), (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [21]:
person_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')] 
person_data_def


[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [12]:
 #the same result
people_array = np.zeros( (5), dtype=person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0), (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [17]:
people_array[3]=('Delta', 73, 205, 34)
people_array[0] = ('Alpha', 65, 112, 23)
people_array

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34),
       (b'',  0.,   0.,  0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [18]:
people_array[1:3]

array([(b'', 0., 0., 0), (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [19]:
people_array['age']   #like df

array([23,  0,  0, 34,  0], dtype=int64)

In [24]:
people_big_array=np.zeros((4,3,2),dtype=person_data_def)
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [26]:
people_big_array['age']    # what is shape?

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [29]:
people_big_array[['age','height']]

array([[[(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)]],

       [[(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)]],

       [[(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)]],

       [[(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)],
        [(0, 0.), (0, 0.)]]],
      dtype={'names': ['age', 'height'], 'formats': ['<i8', '<f8'], 'offsets': [22, 6], 'itemsize': 30})

In [30]:
people_big_array[0]['age']

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [31]:
people_big_array[0].age    # to solve this problem  make recored array 

AttributeError: 'numpy.ndarray' object has no attribute 'age'

In [40]:
people_recold_array=np.rec.array( [('delta',73,205,34),('alpha',44,424,30)],dtype=person_data_def)
people_recold_array

rec.array([(b'delta', 73., 205., 34), (b'alpha', 44., 424., 30)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [41]:
people_recold_array[0].age

34

In [42]:
people_recold_array.shape

(2,)

In [44]:
people_recold_array2=np.rec.array( np.zeros((4),dtype=person_data_def))
people_recold_array2

rec.array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
           (b'', 0., 0., 0)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])


# Please think a little about the Pandas dataframe backbone :)