# Splitting arrays
  split

In [2]:
import numpy as np


# split    
for information, please see: https://numpy.org/doc/stable/reference/generated/numpy.split.html

In [5]:
array = np.arange(60)
array.shape=(5,3,4)
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

How the split function will be working?!
a (5,3,4)
5 splits based on axise: 1,3,4
3 splits based on axise: ERROR 
3 splits based on axis1: 5,1,4 
2 splits based on axis1: ERROR 
4 splits based on axis2: 5,3,1 
2 splits based on axis2: 5,3,2 
6 splits based on axis2: ERROR


In [10]:
s0=np.split (array, 5, axis=0)  #return list of arrays
s0

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]),
 array([[[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]),
 array([[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]]])]

In [8]:
type(s0)

list

In [11]:
s0[0].shape

(1, 3, 4)

In [13]:
s1=np.split(array,3,axis=1)
s1

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]],
 
        [[24, 25, 26, 27]],
 
        [[36, 37, 38, 39]],
 
        [[48, 49, 50, 51]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]],
 
        [[28, 29, 30, 31]],
 
        [[40, 41, 42, 43]],
 
        [[52, 53, 54, 55]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]],
 
        [[32, 33, 34, 35]],
 
        [[44, 45, 46, 47]],
 
        [[56, 57, 58, 59]]])]

In [15]:
s1[0].shape

(5, 1, 4)

In [16]:
s2=np.split(array,4,axis=2)
s2

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]],
 
        [[24],
         [28],
         [32]],
 
        [[36],
         [40],
         [44]],
 
        [[48],
         [52],
         [56]]]),
 array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]],
 
        [[25],
         [29],
         [33]],
 
        [[37],
         [41],
         [45]],
 
        [[49],
         [53],
         [57]]]),
 array([[[ 2],
         [ 6],
         [10]],
 
        [[14],
         [18],
         [22]],
 
        [[26],
         [30],
         [34]],
 
        [[38],
         [42],
         [46]],
 
        [[50],
         [54],
         [58]]]),
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]],
 
        [[27],
         [31],
         [35]],
 
        [[39],
         [43],
         [47]],
 
        [[51],
         [55],
         [59]]])]

In [17]:
s2[0].shape

(5, 3, 1)

In [18]:
np.split(array,4,axis=0)


ValueError: array split does not result in an equal division

In [19]:
s2=np.split(array,2,axis=2)
s2

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]],
 
        [[24, 25],
         [28, 29],
         [32, 33]],
 
        [[36, 37],
         [40, 41],
         [44, 45]],
 
        [[48, 49],
         [52, 53],
         [56, 57]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]],
 
        [[26, 27],
         [30, 31],
         [34, 35]],
 
        [[38, 39],
         [42, 43],
         [46, 47]],
 
        [[50, 51],
         [54, 55],
         [58, 59]]])]