# Linear Algebra

In [1]:
import numpy as np


In [9]:
left_mat = np.arange(6).reshape((2,3)) 
right_mat = np.arange(15).reshape((3,5))


In [3]:

np.dot(left_mat, right_mat)


array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [4]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])


https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

In [15]:
# transpose 
my_first_matrix.T


matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [19]:
#matrix invers 
my_first_inverse=my_first_matrix.I
my_first_inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [21]:
#should return inverse; floating point values "almost" equal zero
my_first_matrix* my_first_inverse


matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
        [ 5.55111512e-17, -1.38777878e-16,  1.00000000e+00]])

In [22]:
# create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Solve simultaneous linear equations


In [24]:
right_hand_side = np.matrix([[11],
                                [22], 
                                [33]])
right_hand_side

matrix([[11],
        [22],
        [33]])

In [25]:
 # not efficient; use only for small matrices 
solution =my_first_inverse *right_hand_side 
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [26]:
# more efficient for Large matrices 
from numpy.linalg import solve 
solve (my_first_matrix,right_hand_side)


matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [28]:
coeff_matrix = np.matrix([[2, 5, 4], [1, -1, 4], [-4, 3, -1]]) 
rh_side =np.matrix([[10], [20], [5]])
solve(coeff_matrix, rh_side)



matrix([[-3.46534653],
        [-1.08910891],
        [ 5.59405941]])

In [27]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)


EigResult(eigenvalues=array([13.08576474,  2.58000566, -2.66577041]), eigenvectors=matrix([[-0.31542644, -0.95117074, -0.32372474],
        [-0.72306109,  0.30781323, -0.70222933],
        [-0.61456393,  0.02291827,  0.63409484]]))


# for more information about NumPy Linear Algebra
https://numpy.org/doc/stable/reference/routines.linalg.html